---
title: "011-Scrape"
author: "JJayes"
date: "26/01/2022"
output: html_document
---

```{r}
# knitr::purl("code/011-Scrape.Rmd", documentation = 2)

library(tidyverse)
library(rvest)

source("code/fns/get_property_info.R")

tbl_of_links <- read_rds("data/links/list_of_links_complete.rds")

results <- tbl_of_links %>% 
  # head(20) %>% 
  mutate(property_link = paste0("https://www.privateproperty.co.za", property_link)) %>%
  mutate(result = map(property_link, possibly(get_property_info, "failed")))

st <- format(Sys.time(), "%Y-%m-%d-%I-%M-%p")

results %>% 
  write_rds(paste0("data/results/results_test", st, ".rds"), compress = "gz")
```

Chang the head(20) and filename_test

Ones to redo

```{r}
links_to_redo <- results %>% 
  filter(result == "failed")

links_to_redo %>% head(20) %>% pull(property_link)
```


```{r}
results %>% 
  filter(result != "failed") %>% 
  unnest(result) %>% 
  ggplot(aes(price, fill = Property)) +
  geom_density() +
  facet_wrap(~ Property) +
  scale_x_log10(labels = scales::dollar_format()) 
```


```{r}
library(ggridges)

results %>% 
  filter(result != "failed") %>% 
  unnest(result) %>% 
  filter(!is.na(price)) %>% 
  mutate(Property = fct_reorder(Property, price, .fun = "median")) %>% 
  ggplot(aes(x = price, y = Property, fill = Property)) +
  geom_density_ridges(show.legend = F) +
  # facet_wrap(~ Property) +
  scale_x_log10(labels = scales::dollar_format(prefix = "R ")) 

```



```{r}
df_results <- results %>% 
  filter(result != "failed") %>% 
  unnest(result) %>% 
  filter(!is.na(price))

df_median_prices <- df_results %>%
  group_by(Property) %>% 
  summarise(median_price = median(price)) %>% 
  ungroup() %>% 
  arrange(median_price)
```

```{r}
df <- read_rds("data/board-stats.rds")

df %>% 
  select(Property, board_price = Price) %>% 
  inner_join(df_median_prices) %>% 
  ggplot(aes(board_price, median_price, label = Property)) +
  geom_point() +
  geom_text(nudge_y = .1, check_overlap = T) +
  scale_y_log10(labels = scales::dollar_format(prefix = "R ")) +
  scale_x_continuous(labels = scales::dollar_format(prefix = "R ")) +
  geom_smooth(method = "lm", se = F) +
  labs(x = "Price on Monopoly Board",
       y = "Median price of property from PrivateProperty.co.za")
  
```


```{r}

df_results %>% 
  unnest(result_feature) %>% 
  distinct(property_link, key, .keep_all = T) %>% 
  pivot_wider(names_from = key, values_from = value) %>% view

```

